### ISSUE TITLE
[BUG] SKBitmap.SetPixel treating color type rgba8888 as bgra8888

### ISSUE THREAD

**Issue by 0x5b25** [mono/SkiaSharp#958]
**Description**

SKBitmap.SetPixel function treating color type rgba8888 as bgra8888, while color type bgra8888 works correctly.

**Code**

```csharp
SKBitmap testbmp = new SKBitmap(new SKImageInfo(32,32,SKColorType.Rgba8888,SKAlphaType.Premul));
testbmp.SetPixel(0,0,new SKColor(220,0,0,255));
SKColor c = testbmp.GetPixel(0, 0);
```
**Expected Behavior**

testbmp.Bytes[0] == 220
testbmp.Bytes[1] == 0
testbmp.Bytes[2] == 0
testbmp.Bytes[3] == 255
c == ffdc0000

**Actual Behavior**

testbmp.Bytes[0] == 0
testbmp.Bytes[1] == 0
testbmp.Bytes[2] == 220
testbmp.Bytes[3] == 255
c == ff0000dc

**Basic Information**

- Version with issue:  v1.68.0
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - UWP:  Windows 10, version 1803 (17134)

**Comment by xPaw** [comment]
I just ran into this issue when updating from 1.68.2.1 to 2.80.0

**Comment by mattleibow** [comment]
I have been thinking about this and I think what v2 does is the most correct form.

When creating a bitmap with `Rgba8888` the _bytes_ are in the order of RGBA. And for `Bgra8888`, the _bytes_ are in the order BGRA. This allows for a memory buffer to be used and the order to be known. If you were to take a bitmap and copy the pixels back in on itself, the colors will change when using v1 and this is unexpected. 

**Code**
```csharp
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("RGBA:");
        Test(SKColorType.Rgba8888);

        Console.WriteLine("BGRA:");
        Test(SKColorType.Bgra8888);
    }

    private static void Test(SKColorType colorType)
    {
        var bmp = new SKBitmap(1, 1, colorType, SKAlphaType.Premul);
        bmp.Erase(SKColors.Red);

        Console.WriteLine("   OLD:");
        Console.WriteLine("    - color: " + bmp.GetPixel(0, 0));
        Console.WriteLine("    - bytes: " + string.Join(", ", bmp.Bytes));

        bmp.SetPixel(0, 0, bmp.GetPixel(0, 0));

        Console.WriteLine("   NEW:");
        Console.WriteLine("    - color: " + bmp.GetPixel(0, 0));
        Console.WriteLine("    - bytes: " + string.Join(", ", bmp.Bytes));
    }
}
```

**v1** (note the different color with RGBA due to the swapping of the bytes)
```
RGBA:
   OLD:
    - color: #ffff0000
    - bytes: 255, 0, 0, 255
   NEW:
    - color: #ff0000ff
    - bytes: 0, 0, 255, 255
BGRA:
   OLD:
    - color: #ffff0000
    - bytes: 0, 0, 255, 255
   NEW:
    - color: #ffff0000
    - bytes: 0, 0, 255, 255
```

**v2**
```
RGBA:
   OLD:
    - color: #ffff0000
    - bytes: 255, 0, 0, 255
   NEW:
    - color: #ffff0000
    - bytes: 255, 0, 0, 255
BGRA:
   OLD:
    - color: #ffff0000
    - bytes: 0, 0, 255, 255
   NEW:
    - color: #ffff0000
    - bytes: 0, 0, 255, 255
```
